# Generated by Django 4.1.1 on 2022-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websection', models.CharField(blank=True, max_length=255)),
                ('heading1', models.CharField(blank=True, max_length=255)),
                ('heading2', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('attachment_image', models.ImageField(blank=True, upload_to='website/images')),
                ('attachment_file', models.FileField(blank=True, upload_to='website/uploads')),
                ('datafeatured', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
