# Generated by Django 4.1.1 on 2022-09-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecontects',
            options={'verbose_name': 'websiteContent', 'verbose_name_plural': 'websiteContents'},
        ),
    ]
