# Generated by Django 4.1.1 on 2022-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_websitecontects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
