# Generated by Django 4.1.1 on 2022-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='tourdata',
            options={'verbose_name': 'TourData', 'verbose_name_plural': 'TourData'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=models.ImageField(upload_to='destinations'),
        ),
    ]
