# Generated by Django 3.2.14 on 2022-10-11 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('ticket_type', models.CharField(max_length=255)),
                ('adult', models.IntegerField(null=True)),
                ('child', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 18, 20, 24, 803779))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 18, 20, 24, 803779))),
                ('image', models.FileField(upload_to='')),
                ('departureTime', models.CharField(max_length=255)),
                ('return_time', models.DateField(default=datetime.date(2022, 10, 11))),
                ('map_latitude', models.CharField(blank=True, max_length=255)),
                ('map_longtude', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('departure', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursel_image1', models.FileField(upload_to='')),
                ('coursel_image2', models.FileField(upload_to='')),
                ('coursel_image3', models.FileField(upload_to='')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_duration', models.IntegerField()),
                ('package_tour_type', models.CharField(max_length=200)),
                ('package_tour_guide', models.IntegerField()),
                ('package_people_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_detail', models.TextField()),
                ('info_image1', models.FileField(upload_to='')),
                ('info_image2', models.FileField(upload_to='')),
                ('info_video', models.FileField(upload_to='')),
                ('info_destination', models.CharField(max_length=200)),
                ('info_depature_time', models.DateTimeField(auto_now_add=True)),
                ('info_return_time', models.DateTimeField(auto_now_add=True)),
                ('info_depature', models.CharField(max_length=200)),
                ('info_included1', models.CharField(max_length=200)),
                ('info_included2', models.CharField(max_length=200)),
                ('info_included3', models.CharField(max_length=200)),
                ('info_included4', models.CharField(max_length=200)),
                ('info_included5', models.CharField(max_length=200)),
                ('info_excluded1', models.CharField(max_length=200)),
                ('info_excluded2', models.CharField(max_length=200)),
                ('info_excluded3', models.CharField(max_length=200)),
                ('info_excluded4', models.CharField(max_length=200)),
                ('info_excluded5', models.CharField(max_length=200)),
                ('travel_status', models.CharField(max_length=200)),
                ('travel_plan_detail', models.TextField()),
                ('travel_plan_day_title', models.CharField(max_length=200)),
                ('travel_plan_day_time_From', models.DateTimeField(auto_now_add=True)),
                ('travel_plan_day_time_To', models.DateTimeField(auto_now=True)),
                ('travel_plan_day_description_To', models.TextField()),
                ('gallery_image', models.FileField(upload_to='')),
                ('map_latitude', models.CharField(blank=True, max_length=255)),
                ('map_longtude', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapi.package')),
            ],
            options={
                'verbose_name': 'Package_Detail',
                'verbose_name_plural': 'Packages_Details',
            },
        ),
    ]
