# Generated by Django 4.1.1 on 2022-10-19 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('ticket_type', models.CharField(max_length=255)),
                ('adult', models.IntegerField(null=True)),
                ('child', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('sub_image1', models.FileField(blank=True, upload_to='')),
                ('sub_image2', models.FileField(blank=True, upload_to='')),
                ('departureTime', models.DateField(default=datetime.date(2022, 10, 19))),
                ('return_time', models.DateField(default=datetime.date(2022, 10, 19))),
                ('map_latitude', models.CharField(blank=True, max_length=255)),
                ('map_longtude', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('departure', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('blocked', 'blocked')], default='active', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 25, 13, 815787))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 25, 13, 815787))),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursel_image1', models.FileField(upload_to='')),
                ('coursel_image2', models.FileField(upload_to='')),
                ('coursel_image3', models.FileField(upload_to='')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(default='', max_length=200)),
                ('package_price', models.IntegerField(default=0)),
                ('package_duration', models.IntegerField(default=0)),
                ('package_tour_type', models.CharField(default='', max_length=200)),
                ('package_tour_guide', models.IntegerField(default=0)),
                ('package_people_group', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='none')),
                ('info_detail', models.TextField(blank=True, default='none')),
                ('info_image1', models.FileField(default=None, upload_to='')),
                ('info_image2', models.FileField(default=None, upload_to='')),
                ('info_video', models.FileField(blank=True, upload_to='')),
                ('info_destination', models.CharField(default='', max_length=200)),
                ('info_depature_time', models.DateField(default=datetime.date(2022, 10, 19))),
                ('info_return_time', models.DateField(default=datetime.date(2022, 10, 19))),
                ('info_depature', models.CharField(default='', max_length=200)),
                ('info_included1', models.CharField(default='none', max_length=200)),
                ('info_included2', models.CharField(default='none', max_length=200)),
                ('info_included3', models.CharField(default='', max_length=200)),
                ('info_included4', models.CharField(default='', max_length=200)),
                ('info_included5', models.CharField(default='', max_length=200)),
                ('info_excluded1', models.CharField(default='', max_length=200)),
                ('info_excluded2', models.CharField(default='', max_length=200)),
                ('info_excluded3', models.CharField(default='', max_length=200)),
                ('info_excluded4', models.CharField(default='', max_length=200)),
                ('info_excluded5', models.CharField(default='', max_length=200)),
                ('travel_status', models.CharField(default='', max_length=200)),
                ('travel_plan_detail', models.TextField(default='')),
                ('travel_plan_day_title', models.CharField(default='', max_length=200)),
                ('travel_plan_day_time_From', models.CharField(default='10:00', max_length=200)),
                ('travel_plan_day_time_To', models.CharField(default='10:00', max_length=200)),
                ('travel_plan_day_description_To', models.TextField(default='')),
                ('tour_gallery_image1', models.FileField(default=None, upload_to='')),
                ('tour_gallery_image2', models.FileField(default=None, upload_to='')),
                ('tour_gallery_image3', models.FileField(default=None, upload_to='')),
                ('tour_gallery_image4', models.FileField(default=None, upload_to='')),
                ('tour_gallery_image5', models.FileField(default=None, upload_to='')),
                ('map_latitude', models.CharField(blank=True, max_length=255)),
                ('map_longtude', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 25, 13, 815787))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 10, 19, 19, 25, 13, 815787))),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
