# Generated by Django 4.1.1 on 2022-10-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursel_image1', models.FileField(upload_to='')),
                ('coursel_image2', models.FileField(upload_to='')),
                ('coursel_image3', models.FileField(upload_to='')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('title3', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_duration', models.IntegerField()),
                ('package_tour_type', models.CharField(max_length=200)),
                ('package_tour_guide', models.IntegerField()),
                ('package_people_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_detail', models.TextField()),
                ('info_image1', models.FileField(upload_to='')),
                ('info_image2', models.FileField(upload_to='')),
                ('info_video', models.FileField(upload_to='')),
                ('info_destination', models.CharField(max_length=200)),
                ('info_depature_time', models.DateTimeField(auto_now_add=True)),
                ('info_return_time', models.DateTimeField(auto_now_add=True)),
                ('info_depature', models.CharField(max_length=200)),
                ('info_included1', models.CharField(max_length=200)),
                ('info_included2', models.CharField(max_length=200)),
                ('info_included3', models.CharField(max_length=200)),
                ('info_included4', models.CharField(max_length=200)),
                ('info_included5', models.CharField(max_length=200)),
                ('info_excluded1', models.CharField(max_length=200)),
                ('info_excluded2', models.CharField(max_length=200)),
                ('info_excluded3', models.CharField(max_length=200)),
                ('info_excluded4', models.CharField(max_length=200)),
                ('info_excluded5', models.CharField(max_length=200)),
                ('travel_status', models.CharField(max_length=200)),
                ('travel_plan_detail', models.TextField()),
                ('travel_plan_day_title', models.CharField(max_length=200)),
                ('travel_plan_day_time_From', models.DateTimeField(auto_now_add=True)),
                ('travel_plan_day_time_To', models.DateTimeField(auto_now=True)),
                ('travel_plan_day_description_To', models.TextField()),
                ('gallery_image', models.FileField(upload_to='')),
                ('map_latitude', models.CharField(blank=True, max_length=255)),
                ('map_longtude', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapi.package')),
            ],
            options={
                'verbose_name': 'Package_Detail',
                'verbose_name_plural': 'Packages_Details',
            },
        ),
        migrations.CreateModel(
            name='Destination_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
                ('departure', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('return_time', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapi.destination')),
            ],
            options={
                'verbose_name': 'Destination_Detail',
                'verbose_name_plural': 'Destinations_Details',
            },
        ),
    ]
