# Generated by Django 3.2.14 on 2022-10-18 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={},
        ),
        migrations.AddField(
            model_name='destination',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('blocked', 'blocked')], default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='sub_image1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='sub_image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 48, 11, 823778)),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='info_depature',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_depature_time',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AddField(
            model_name='package',
            name='info_destination',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='info_excluded1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_excluded2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_excluded3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_excluded4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_excluded5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_image1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='info_image2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='info_included1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_included2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_included3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_included4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_included5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='info_return_time',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AddField(
            model_name='package',
            name='info_video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='map_latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='map_longtude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_gallery_image1',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_gallery_image2',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_gallery_image3',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_gallery_image4',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_gallery_image5',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan_day_description_To',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan_day_time_From',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan_day_time_To',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan_day_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 48, 11, 823778)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 48, 11, 823778)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departureTime',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='return_time',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 15, 48, 11, 823778)),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_duration',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_people_group',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_tour_guide',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_tour_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Package_Details',
        ),
    ]
