# Generated by Django 4.1.1 on 2022-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='map_latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='package_details',
            name='map_longtude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
