# Generated by Django 3.2.14 on 2022-10-11 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0002_auto_20221011_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 18, 22, 8, 952053)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departureTime',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 18, 22, 8, 952053)),
        ),
    ]
