# Generated by Django 3.0.5 on 2022-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0003_auto_20220926_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='destination_detail',
            options={'verbose_name': 'Destination_Detail', 'verbose_name_plural': 'Destinations_Details'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Heroes'},
        ),
        migrations.AlterModelOptions(
            name='package_details',
            options={'verbose_name': 'Package_Detail', 'verbose_name_plural': 'Packages_Details'},
        ),
    ]
