# Generated by Django 3.2.14 on 2022-10-11 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0004_auto_20221011_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='sub_image1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='sub_image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 19, 20, 16, 614747)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 19, 20, 16, 614747)),
        ),
    ]
