# Generated by Django 3.2.14 on 2022-10-11 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0005_auto_20221011_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('blocked', 'blocked')], default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 19, 40, 58, 201365)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 19, 40, 58, 201365)),
        ),
    ]
