# Generated by Django 4.1.1 on 2022-10-13 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0006_auto_20221011_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 12, 32, 38, 314415)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departureTime',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='return_time',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 12, 32, 38, 314415)),
        ),
    ]
