# Generated by Django 3.2.14 on 2022-10-18 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0010_auto_20221018_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 10, 14, 275334)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 10, 14, 275334)),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 10, 14, 274334)),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_detail',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 16, 10, 14, 274334)),
        ),
    ]
