# Generated by Django 3.2.14 on 2022-10-20 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0015_auto_20221018_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 42, 33, 446999)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departureTime',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='return_time',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 42, 33, 446999)),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 42, 33, 446999)),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_depature_time',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_included1',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_included2',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_return_time',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_duration',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_people_group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_tour_guide',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 42, 33, 446999)),
        ),
    ]
