# Generated by Django 4.1.2 on 2022-10-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapi', '0016_auto_20221020_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan2_day_description_To',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan2_day_time_From',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan2_day_time_To',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan2_day_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan2_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan3_day_description_To',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan3_day_time_From',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan3_day_time_To',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan3_day_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan3_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan4_day_description_To',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan4_day_time_From',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan4_day_time_To',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan4_day_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan4_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan5_day_description_To',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan5_day_time_From',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan5_day_time_To',
            field=models.CharField(default='10:00', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan5_day_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_plan5_detail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 12, 45, 44, 892386)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='departureTime',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='return_time',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 12, 45, 44, 892386)),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 12, 45, 44, 891386)),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_depature_time',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='package',
            name='info_return_time',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 12, 45, 44, 891386)),
        ),
    ]
